title: BG Software
url: http://bg.software
baseurl: ''
collections:
  authors:
sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
plugins:
  - jekyll-seo-tag
twitter:
  username: BGSoftwareInc
  card: summary
social:
  name: BG Software
  links:
    - https://twitter.com/BGSoftwareInc
    - https://www.facebook.com/BGSoftwareInc
    - https://www.linkedin.com/company/bgsoftwareinc
    - https://www.youtube.com/channel/UCkeGLG82Ydd6GnoLh1QPfag
google_analytics: UA-138417210-2