- name: Custom Software
  point: What we do is find out exactly what you’d like to achieve with your business, show you the possibilities, then talk with you about creating software that solves your problem. Our developers have many resources to build things. The best part? You’re the expert on your business. You’ll be our partner in the project.
  points:
    - Database Design and Implementation
    - Web Development
    - Mobile Applications
    - Application Management & Support
- name: Security
  point: It means a lot more than a login and a password. You want your system to be as secure as possible. We can help by creating tools to not only make sure the person accessing your program(s) is who they say they are, but also verify what each user has access to. We have a lot of experience in this area.
  points:
    - Single Sign-On
    - Authorization
    - Authentication
- name: Data Integration
  point: Information comes at us from many sources. At BG Software, we can personalize a program for you which can gather up business records from legacy systems, old databases, and your brand-new data to show you one unified view. We can gather all of it and present it in a way that works for you.
  points:
    - APIs
    - Automation Services
    - Scheduled Tasks