- name   : Software Development
  image  : software_development_icon.png
  point  : We find out what you’d like to achieve with your business, show you the possibilities, then talk with you about creating software that solves your problem.
  points :
    - Database Design and Implementation
    - Mobile Applications
    - Application Management & Support
- name   : Security
  image  : security_icon.png
  point  : We can create tools to not only make sure the person accessing your program(s) is who they say they are, but also verify what each user has access to.
  points :
    - Single Sign-On
    - Authorization
    - Authentication
- name   : System Integrations
  image  : data_integration_icon.png
  point  : We can gather up business records from legacy systems, old databases, and your brand-new data to show you one unified view.
  points :
    - APIs
    - Automation Services
    - Scheduled Tasks
- name   : DevOps
  image  : devops_icon.png
  point  : As systems grow, so too does the complexity of development operations. We’re also experts in automating testing, building, and deploying software using continuous-integration / continuous-delivery (CI/CD) tools.
  points :
- name   : Data Warehousing
  image  : data_warehousing_icon.png
  point  : The software we author is driven by big data. Our SQL experts make reporting, aggregating, and sharing data via web services easy.
  points :
- name   : Back-End Development
  image  : back-end_development_icon.png
  point  : As back-end developers, our team works with a variety of languages, including JavaScript, Python, and even ColdFusion. Our specialty is integrations wherein data needs to be shared between multiple disparate systems.
  points :